project:
  type: website
  output-dir: docs

website:
  title: "Kimberley D. Lemmen"
  favicon: media/ciliateicon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: pubs.qmd
        text: Publications
      - href: "media/Lemmen_CV_General.pdf"
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: Yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

